leasing_service/urls.py
from django.urls import path
from . import views

app_name = 'leasing_service'

urlpatterns = [
    path('submit-lease-request/<int:property_id>/', views.submit_lease_request, name="submit_lease_request"),
    path('manage-lease-requests/', views.manage_lease_requests, name="manage_lease_requests"),
    path('my-leases/', views.my_leases, name="my_leases"),
    path('cancel-lease/<int:lease_id>/', views.cancel_lease, name='cancel_lease'),
]

listing_service/urls.py
from django.urls import include, path
from . import views

app_name = 'listing_service'

urlpatterns = [
    path('', views.property_listing, name="property_listing"),
    path('add/', views.add_property, name="add_property"),
    path('property/<int:property_id>/', views.property_details, name='property_details'),
    path('property/<int:property_id>/edit/', views.edit_property, name="edit_property"),
    path('property/<int:property_id>/delete/', views.delete_property, name="delete_property"),
	  path('property/<int:property_id>/walkscore/', views.get_walk_score, name='get_walk_score'),
    path('create/', views.create_collection, name="create_collection"),
    path('collections/', views.collection_listing, name="collection_listing"),
    path('collections/<int:collection_id>/', views.collection_details, name='collection_details'),
    path('collections/<int:collection_id>/edit/', views.edit_collection, name="edit_collection"),
    path('collections/<int:collection_id>/delete/', views.delete_collection, name="delete_collection"),
    path('collections/my_collections/', views.my_collections, name="my_collections"),
    path('collections/request-access/<int:collection_id>/', views.request_collection_access, name='request_collection_access'),
    path('collections/manage-access-requests/', views.manage_access_requests, name='manage_access_requests'),
    path('search_properties/', views.search_properties, name='search_properties'),
    path('collections/<int:collection_id>/revoke_access/<int:user_id>/', views.revoke_collection_access, name='revoke_collection_access'),
    path('get_presigned_url/', views.get_presigned_url, name='get_presigned_url'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import landing, home, login_cancelled, login_cancelled_3rdparty

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/3rdparty/login/cancelled/", login_cancelled_3rdparty, name="thirdparty_login_cancelled"),
    path('accounts/social/login/cancelled/', login_cancelled, name="socialaccount_login_cancelled"),
    path('accounts/', include('allauth.urls')),
	path("user/", include("user_service.urls")),
    path('listings/', include('listing_service.urls')),
    path("reviews/", include("review_service.urls", namespace="review_service")),
    path('leasing/', include('leasing_service.urls')),
    path('notifications/', include('notification_service.urls')),
    path('', landing, name='home'),
]

notification_service/urls.py
from django.urls import path
from . import views

app_name = 'notification_service'

urlpatterns = [
    path('', views.notifications, name="notifications"),
]

user_service/urls.py
from django.urls import path
from .views import reset_profile_image, view_profile, edit_profile, librarian_dashboard, update_user_role, manage_users, guest_login


app_name = "user_service"  # This enables the namespace "user_service"

urlpatterns = [
    path("librarian-dashboard/", librarian_dashboard, name="librarian_dashboard"),
    path("manage-users/", manage_users, name="manage_users"),  # user managing page
    path("update-role/<int:user_id>/", update_user_role, name="update_user_role"),  # role change
    path("profile/", view_profile, name="view_profile"),
	path("profile/edit/", edit_profile, name="edit_profile"),
    path("profile/reset-image/", reset_profile_image, name="reset_profile_image"),
    path('guest-login/', guest_login, name='guest_login'),
]

mysite/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.urls import reverse

@login_required
def home(request):
    user = request.user

    if getattr(user, "role", None) == "librarian":
        return render(request, "home_librarian.html", {"user": user})  # 사서 화면
    else:
        return render(request, "home_patron.html", {"user": user})  # 일반 사용자 화면

def landing(request):
        return render(request, "landing/landing.html")  # 사서 화면
    
def login_cancelled(request):
    return render(request, "account/login.html")

def login_cancelled_3rdparty(request):
    return render(request, "account/login.html")

mysite/templates/components/footer.html
<footer class="footer">
  <div class="footer-left">
    <p class="footer-text">
      &copy; HoosHousing LLC. {% now 'Y' %}
    </p>
  </div>
  <div class="footer-middle">
    <p>DEMO ENVIRONMENT NOTICE: This application was developed as an academic project and is presented for demonstration purposes only. The system is not actively monitored or maintained for production use. Please refrain from submitting any sensitive or personal information.</p>
  </div>
  <div class="footer-right">
    <div class="socials">
    </div>
  </div>
</footer>

mysite/templates/components/navbar.html
{% load static %}

<nav class="navbar">
    <a href="{% url 'home' %}" class="navbar-brand">
        <div class="navbar-left">
            <img class="logo" src="{% static 'mysite/assets/logo.png' %}" alt="HoosHousing? Logo"/>
            <span class="logotext">HoosHousing?</span>
        </div>
    </a>

    <!-- Hamburger menu icon -->
    <div class="hamburger">
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
    </div>

    <div class="navbar-right">
        {% if user.is_authenticated %}
            <a href="{% url 'listing_service:property_listing' %}" class="nav-item">Listings</a>
            <a href="{% url 'listing_service:collection_listing' %}" class="nav-item">Collections</a>

            {% if user.username != 'guest' %}
                <a href="{% url 'listing_service:my_collections' %}" class="nav-item">My Collections</a>
                <a href="{% url 'leasing_service:my_leases' %}" class="nav-item">My Leases</a>
            {% endif %}
            
            <div class="dropdown">
                <button class="dropbtn">
                    <a href="{% url 'user_service:view_profile' %}" style="display:inline-block;">
                        {% if user.profile_image %}
                            <img src="{{ user.profile_image }}" class="profile-pic" alt="Profile Picture">
                        {% else %}
                            <img src="{% static 'mysite/assets/default-profile.png' %}" class="profile-pic" alt="Default Profile">
                        {% endif %}
                    </a>
                    <span>{{ user.username|default:"User" }}</span>
                </button>
                <div class="dropdown-content">
                    {% if user.username != 'guest' %}
                        <a href="{% url 'notification_service:notifications' %}">Notifications</a>
                        {% if user.role == 'librarian' %}
                            <a href="{% url 'leasing_service:manage_lease_requests' %}">Lease Requests</a>
                            <a href="{% url 'listing_service:manage_access_requests' %}">Access Requests</a>
                            <a href="{% url 'user_service:manage_users' %}">Manage Users</a>
                        {% endif %}
                    {% endif %}
                    <a href="{% url 'account_logout' %}">Sign Out</a>
                </div>
            </div>            
        {% else %}
            <a href="{% url 'account_login' %}?next={% url 'listing_service:property_listing' %}" class="nav-item">Listings</a>
            <a href="{% url 'account_login' %}?next={% url 'listing_service:collection_listing' %}" class="nav-item">Collections</a>
            <a href="{% url 'account_login' %}" class="nav-item">Sign In</a>
        {% endif %}
    </div>
</nav>